### Loading and cleaning data

In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

# using encoding = "ISO-8859-1" to avoid pandas encoding error
funding_rounds = pd.read_csv("rounds2.csv", encoding = "ISO-8859-1")
companies = pd.read_csv("companies.txt", sep="\t", encoding = "ISO-8859-1")

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/Organization/-Qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/Organization/-The-One-Of-Them-Inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/Organization/004-Technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
5,/Organization/01Games-Technology,01Games Technology,http://www.01games.hk/,Games,operating,HKG,NaN,Hong Kong,Hong Kong,NaN
6,/Organization/0Ndine-Biomedical-Inc,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-01-1997
7,/Organization/0Xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
8,/Organization/1,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
9,/Organization/1-2-3-Listo,"1,2,3 Listo",http://www.123listo.com,E-Commerce,operating,CHL,12,Santiago,Las Condes,01-01-2012

### Checking how the dataframes look like for the funding rounds and the companies

In [6]:
#funding rounds
print(funding_rounds.head())

#shape
print(funding_rounds.shape)

#info
print(funding_rounds.info(), "\n")

                     company_permalink  \
0                  /organization/-fame
1               /ORGANIZATION/-QOUNTER
2               /organization/-qounter
3  /ORGANIZATION/-THE-ONE-OF-THEM-INC-
4                /organization/0-6-com

                           funding_round_permalink funding_round_type  \
0  /funding-round/9a01d05418af9f794eebff7ace91f638            venture
1  /funding-round/22dacff496eb7acb2b901dec1dfe5633            venture
2  /funding-round/b44fbb94153f6cdef13083530bb48030               seed
3  /funding-round/650b8f704416801069bb178a1418776b            venture
4  /funding-round/5727accaeaa57461bd22a9bdd945382d            venture

  funding_round_code   funded_at  raised_amount_usd
0                  B  05-01-2015         10000000.0
1                  A  14-10-2014                NaN
2                NaN  01-03-2014           700000.0
3                  B  30-01-2014          3406878.0
4                  A  19-03-2008          2000000.0
(114949, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114949 entries, 0 to 114948
Data columns (total 6 columns):
company_permalink          114949 non-null object
funding_round_permalink    114949 non-null object
funding_round_type         114949 non-null object
funding_round_code         31140 non-null object
funded_at                  114949 non-null object
raised_amount_usd          94959 non-null float64
dtypes: float64(1), object(5)
memory usage: 5.3+ MB
None

In [7]:
#companies
print(companies.head())

#shape
print(companies.shape)

#info
print(companies.info(), "\n")

                             permalink                    name  \
0                  /Organization/-Fame                   #fame
1               /Organization/-Qounter                :Qounter
2  /Organization/-The-One-Of-Them-Inc-  (THE) ONE of THEM,Inc.
3                /Organization/0-6-Com                 0-6.com
4       /Organization/004-Technologies        004 Technologies

                        homepage_url  \
0                 http://livfame.com
1             http://www.qounter.com
2                http://oneofthem.jp
3                 http://www.0-6.com
4  http://004gmbh.de/en/004-interact

                                       category_list     status country_code  \
0                                              Media  operating          IND
1  Application Platforms|Real Time|Social Network...  operating          USA
2                                  Apps|Games|Mobile  operating          NaN
3                                        Curated Web  operating          CHN
4                                           Software  operating          USA

  state_code                 region           city  founded_at
0         16                 Mumbai         Mumbai         NaN
1         DE             DE - Other  Delaware City  04-09-2014
2        NaN                    NaN            NaN         NaN
3         22                Beijing        Beijing  01-01-2007
4         IL  Springfield, Illinois      Champaign  01-01-2010
(66368, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66368 entries, 0 to 66367
Data columns (total 10 columns):
permalink        66368 non-null object
name             66367 non-null object
homepage_url     61310 non-null object
category_list    63220 non-null object
status           66368 non-null object
country_code     59410 non-null object
state_code       57821 non-null object
region           58338 non-null object
city             58340 non-null object
founded_at       51147 non-null object
dtypes: object(10)
memory usage: 5.1+ MB
None

### both have quite a few missing values so lets proceed to do some cleanup